# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x04\x64\x65mo\"%\n\rBinaryRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1d\n\x0b\x42inaryReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"2\n\x0b\x44ivideReply\x12\x10\n\x08quotient\x18\x01 \x01(\x05\x12\x11\n\tremainder\x18\x02 \x01(\x05\".\n\x0cPowerRequest\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x05\x12\x10\n\x08\x65xponent\x18\x02 \x01(\x05\"\x19\n\x0cUnaryRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"2\n\rFactorialStep\x12\x0c\n\x04step\x18\x01 \x01(\x05\x12\x13\n\x0b\x61\x63\x63umulator\x18\x02 \x01(\x03\"\x12\n\x05Value\x12\t\n\x01v\x18\x01 \x01(\x01\",\n\nStatsReply\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\x10\n\x08variance\x18\x02 \x01(\x01\x32\xbd\x02\n\nCalculator\x12-\n\x03\x41\x64\x64\x12\x13.demo.BinaryRequest\x1a\x11.demo.BinaryReply\x12\x32\n\x08Subtract\x12\x13.demo.BinaryRequest\x1a\x11.demo.BinaryReply\x12\x32\n\x08Multiply\x12\x13.demo.BinaryRequest\x1a\x11.demo.BinaryReply\x12.\n\x05Power\x12\x12.demo.PowerRequest\x1a\x11.demo.BinaryReply\x12\x30\n\x06\x44ivide\x12\x13.demo.BinaryRequest\x1a\x11.demo.DivideReply\x12\x36\n\tFactorial\x12\x12.demo.UnaryRequest\x1a\x13.demo.FactorialStep0\x01\x32<\n\x05Stats\x12\x33\n\x10\x44\x65scriptiveStats\x12\x0b.demo.Value\x1a\x10.demo.StatsReply(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYREQUEST']._serialized_start=26
  _globals['_BINARYREQUEST']._serialized_end=63
  _globals['_BINARYREPLY']._serialized_start=65
  _globals['_BINARYREPLY']._serialized_end=94
  _globals['_DIVIDEREPLY']._serialized_start=96
  _globals['_DIVIDEREPLY']._serialized_end=146
  _globals['_POWERREQUEST']._serialized_start=148
  _globals['_POWERREQUEST']._serialized_end=194
  _globals['_UNARYREQUEST']._serialized_start=196
  _globals['_UNARYREQUEST']._serialized_end=221
  _globals['_FACTORIALSTEP']._serialized_start=223
  _globals['_FACTORIALSTEP']._serialized_end=273
  _globals['_VALUE']._serialized_start=275
  _globals['_VALUE']._serialized_end=293
  _globals['_STATSREPLY']._serialized_start=295
  _globals['_STATSREPLY']._serialized_end=339
  _globals['_CALCULATOR']._serialized_start=342
  _globals['_CALCULATOR']._serialized_end=659
  _globals['_STATS']._serialized_start=661
  _globals['_STATS']._serialized_end=721
# @@protoc_insertion_point(module_scope)
