# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculator_pb2 as calculator__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculatorStub(object):
    """────────────────────────────
    1.  Basic arithmetic service
    ────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/demo.Calculator/Add',
                request_serializer=calculator__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calculator__pb2.BinaryReply.FromString,
                _registered_method=True)
        self.Subtract = channel.unary_unary(
                '/demo.Calculator/Subtract',
                request_serializer=calculator__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calculator__pb2.BinaryReply.FromString,
                _registered_method=True)
        self.Multiply = channel.unary_unary(
                '/demo.Calculator/Multiply',
                request_serializer=calculator__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calculator__pb2.BinaryReply.FromString,
                _registered_method=True)
        self.Power = channel.unary_unary(
                '/demo.Calculator/Power',
                request_serializer=calculator__pb2.PowerRequest.SerializeToString,
                response_deserializer=calculator__pb2.BinaryReply.FromString,
                _registered_method=True)
        self.Divide = channel.unary_unary(
                '/demo.Calculator/Divide',
                request_serializer=calculator__pb2.BinaryRequest.SerializeToString,
                response_deserializer=calculator__pb2.DivideReply.FromString,
                _registered_method=True)
        self.Factorial = channel.unary_stream(
                '/demo.Calculator/Factorial',
                request_serializer=calculator__pb2.UnaryRequest.SerializeToString,
                response_deserializer=calculator__pb2.FactorialStep.FromString,
                _registered_method=True)


class CalculatorServicer(object):
    """────────────────────────────
    1.  Basic arithmetic service
    ────────────────────────────
    """

    def Add(self, request, context):
        """Unary RPCs (share the same request / reply types)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Power(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Division — uses a specialised reply (quotient + remainder)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Factorial(self, request, context):
        """Server-streaming RPC – emits each step of a factorial calculation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=calculator__pb2.BinaryRequest.FromString,
                    response_serializer=calculator__pb2.BinaryReply.SerializeToString,
            ),
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=calculator__pb2.BinaryRequest.FromString,
                    response_serializer=calculator__pb2.BinaryReply.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=calculator__pb2.BinaryRequest.FromString,
                    response_serializer=calculator__pb2.BinaryReply.SerializeToString,
            ),
            'Power': grpc.unary_unary_rpc_method_handler(
                    servicer.Power,
                    request_deserializer=calculator__pb2.PowerRequest.FromString,
                    response_serializer=calculator__pb2.BinaryReply.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=calculator__pb2.BinaryRequest.FromString,
                    response_serializer=calculator__pb2.DivideReply.SerializeToString,
            ),
            'Factorial': grpc.unary_stream_rpc_method_handler(
                    servicer.Factorial,
                    request_deserializer=calculator__pb2.UnaryRequest.FromString,
                    response_serializer=calculator__pb2.FactorialStep.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.Calculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """────────────────────────────
    1.  Basic arithmetic service
    ────────────────────────────
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Calculator/Add',
            calculator__pb2.BinaryRequest.SerializeToString,
            calculator__pb2.BinaryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Calculator/Subtract',
            calculator__pb2.BinaryRequest.SerializeToString,
            calculator__pb2.BinaryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Calculator/Multiply',
            calculator__pb2.BinaryRequest.SerializeToString,
            calculator__pb2.BinaryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Power(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Calculator/Power',
            calculator__pb2.PowerRequest.SerializeToString,
            calculator__pb2.BinaryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Calculator/Divide',
            calculator__pb2.BinaryRequest.SerializeToString,
            calculator__pb2.DivideReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Factorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/demo.Calculator/Factorial',
            calculator__pb2.UnaryRequest.SerializeToString,
            calculator__pb2.FactorialStep.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StatsStub(object):
    """────────────────────────────
    2.  Statistics service
    ────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescriptiveStats = channel.stream_unary(
                '/demo.Stats/DescriptiveStats',
                request_serializer=calculator__pb2.Value.SerializeToString,
                response_deserializer=calculator__pb2.StatsReply.FromString,
                _registered_method=True)


class StatsServicer(object):
    """────────────────────────────
    2.  Statistics service
    ────────────────────────────
    """

    def DescriptiveStats(self, request_iterator, context):
        """Client streams numbers, server replies once with mean & variance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescriptiveStats': grpc.stream_unary_rpc_method_handler(
                    servicer.DescriptiveStats,
                    request_deserializer=calculator__pb2.Value.FromString,
                    response_serializer=calculator__pb2.StatsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.Stats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.Stats', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Stats(object):
    """────────────────────────────
    2.  Statistics service
    ────────────────────────────
    """

    @staticmethod
    def DescriptiveStats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/demo.Stats/DescriptiveStats',
            calculator__pb2.Value.SerializeToString,
            calculator__pb2.StatsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
